import "./App.scss";
import Home from "./components/Home/Home";
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import PageNotFound from "./components/PageNotFound/PageNotFound";
import CreateStory from "./components/Home/home-stories/create-story/create-story";
import OtherPages from "./components/OtherPages/OtherPages";
import { useEffect, useState } from "react";

// Register the service worker (this gets auto-generated by vite-plugin-pwa)
if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker
      .register("/X-and-O/sw.js")
      .then((res) => {
        console.log("service work is run", res);
      })
      .catch((err) => {
        console.log("service work is run", err);
      });
  });
}

function App() {
  const [deferredPrompt, setDeferredPrompt]: any = useState(null);
  const [showInstallButton, setShowInstallButton] = useState(false);

  // Handle install prompt
  useEffect(() => {
    const handler = (e: any) => {
      e.preventDefault();
      setDeferredPrompt(e);
      console.log("🔥 beforeinstallprompt fired", e);
      setShowInstallButton(true);
    };

    window.addEventListener("beforeinstallprompt", handler);

    return () => {
      window.removeEventListener("beforeinstallprompt", handler);
    };
  }, []);

  const handleInstallClick = async () => {
    if (!deferredPrompt) return;

    deferredPrompt.prompt();
    const { outcome } = await deferredPrompt.userChoice;
    console.log(`User response to install prompt: ${outcome}`);

    setDeferredPrompt(null);
    setShowInstallButton(false);
  };

  return (
    <>
      {showInstallButton && (
        <div className="flexCenter mt-2">
          <button
            onClick={handleInstallClick}
            className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded mb-4 transition-colors duration-300"
          >
            تحميل التطبيق
          </button>
        </div>
      )}

      <Router>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/Facebook/" element={<Home />} />
          <Route path="/Facebook/create-story/" element={<CreateStory />} />
          <Route
            path="/Facebook/videos/"
            element={<OtherPages pageName="Videos" />}
          />
          <Route
            path="/Facebook/groups/"
            element={<OtherPages pageName="Groups" />}
          />
          <Route
            path="/Facebook/gaming/"
            element={<OtherPages pageName="Gaming" />}
          />
          <Route path="*" element={<PageNotFound />} />
        </Routes>
      </Router>
    </>
  );
}

export default App;
