export const bgColorsArray = [
  { value: "linear-gradient(white, white)" },
  { value: "linear-gradient(to top left, grey, white" },
  { value: "linear-gradient(to top left, blue, yellow" },
  { value: "linear-gradient(to top left, green, red" },
  { value: "linear-gradient(to top left, black, white" },
  { value: "linear-gradient(to top left, yellow, red" },
  { value: "linear-gradient(to top left, brown, blueviolet" },
  { value: "linear-gradient(to top left, pink, red" },
  { value: "linear-gradient(to top left, gold, black" },
  { value: "linear-gradient(to top left, blue, black" },
  { value: "linear-gradient(to top left, red, black" },
  { value: "linear-gradient(to top left, green, blue" },
  { value: "linear-gradient(to top left, red, yellow" },
];
